### ISSUE TITLE
this example works only with package-lock.json on the branch. nextjs + typescript + emotion

### ISSUE THREAD

**Issue by fake364** [ben-rogerson/twin.examples#82] opened 2022-01-06 21:13 UTC
I couldn't integrate twin macro into my nextjs project. It shows
./styles/GlobalStyles.tsx
TypeError: Cannot read property 'uid' of undefined
It is also reproducible in your repo.
**How to reproduce:**
Just try to remove node modules and package-lock, and it creates a new lock with some differences which broke your example too

**Comment by ben-rogerson** [comment] 2022-01-06 22:47
I've reproduced the issue on newer versions of NPM.
Dropping back to v6.14.10 allows next.js to build.

```shell
❯ nvm use 14
Now using node v14.15.4 (npm v6.14.10)
```

Seems to be an issue with Twin - when `import tw from 'twin.macro'` is removed, the error isn't shown.

I'll have to troubleshoot this some more, right now I'm in the middle of a big twin update, so I'll take a look afterwards.

**Comment by ben-rogerson** [comment] 2022-01-20 07:07
This error was fixed in next.js:

```js
npm i next@12.0.8
# or
npm i next@latest
```

[Ref](https://github.com/ben-rogerson/twin.macro/issues/606)

**Closed by ben-rogerson** 2022-01-20 07:07 UTC
